export const PAGE_TITLE = "Split The Bill";
export const SERIALNO = "S. No.";
export const OWES = "owes";
export const WHOPAID = "Who Paid";
export const AMOUNTPAID = "Amount Paid";
export const DESC = "Description";
export const ADD_EXPENSE = "Add Expense";
export const TOTAL_EXPENSE = "Total Expense";
export const AVG_EXPENSE = "Per Head Expense is: ";
